apiVersion: v1
kind: Service
metadata:
  name: prd-matrix
  labels:
    app: prd-matrix
spec:
  #type: LoadBalancer
  #type: ClusterIP
  type: NodePort
  ports:
  - port: 80
    #targetPort: http-server
    targetPort: 8080
  selector:
    app: prd-matrix
